export const websites = [
    {
        id:1,
        image:'./images/1.png',
        tools:'html',
        built:'#HTML #CSS #responsive',
        title:'404 Not Found',
        exp:'In this project.I work with HTML and CSS to create a responsive web page.This page is similar with a page. This design is from devChallengers.io',
        demo:'https://venky-cs.github.io/404-not-found/',
        code:'https://github.com/venky-cs/404-not-found',
    },
    {
        id:2,
        image:'./images/2.png',
        tools:'html',
        built:'#HTML #CSS #responsive',
        title:'My Team Page',
        exp:'In this project.I work with HTML and CSS to create a responsive web page.This page is similar with a page. This design is from devChallengers.io',
        demo:'https://venky-cs.github.io/my-team-page/',
        code:'https://github.com/venky-cs/my-team-page',
    },
    {
        id:3,
        image:'./images/3.png',
        tools:'js',
        built:'#HTML #CSS #Js #responsive',
        title:'Interior Consultant',
        exp:'In this project.I work with HTML and CSS to create a responsive web page.This page is similar with a page. This design is from devChallengers.io',
        demo:'https://venky-cs.github.io/interior-consultant/',
        code:'https://github.com/venky-cs/interior-consultant',
    },
    {
        id:4,
        image:'./images/4.png',
        tools:'html',
        built:'#HTML #CSS #responsive',
        title:'Recipe Page',
        exp:'In this project.I work with HTML and CSS to create a responsive web page.This page is similar with a page. This design is from devChallengers.io',
        demo:'https://venky-cs.github.io/recipe-page/',
        code:'https://github.com/venky-cs/recipe-page',
    },
    {
        id:5,
        image:'./images/5.png',
        tools:'html',
        built:'#HTML #CSS #responsive',
        title:'My Gallery',
        exp:'In this project.I work with HTML and CSS to create a responsive web page.This page is similar with a page. This design is from devChallengers.io',
        demo:'https://venky-cs.github.io/my-team-gallery/',
        code:'https://github.com/venky-cs/my-team-gallery',
    },
    {
        id:6,
        image:'./images/6.png',
        tools:'js',
        built:'#HTML #CSS #Js #responsive',
        title:'Checkout Page',
        exp:'In this project.I work with HTML and CSS to create a responsive web page.This page is similar with a page. This design is from devChallengers.io',
        demo:'https://venky-cs.github.io/checkout-page/',
        code:'https://github.com/venky-cs/checkout-page',
    },
    {
        id:7,
        image:'./images/7.png',
        tools:'js',
        built:'#HTML #CSS #Js #responsive',
        title:'Edie Homepage',
        exp:'In this project.I work with HTML and CSS to create a responsive web page.This page is similar with a page. This design is from devChallengers.io',
        demo:'https://venky-cs.github.io/edie-homepage/',
        code:'https://github.com/venky-cs/edie-homepage',
    },
    {
        id:8,
        image:'./images/8.png',
        tools:'react',
        built:'#HTML #CSS #React #responsive',
        title:'Portfolio',
        exp:'In this project.I work with HTML and CSS to create a responsive web page.This page is similar with a page. This design is from devChallengers.io',
        demo:'',
        code:'https://github.com/venky-cs/portfolio',
    },
]